"""autogenerated by genpy from manta/CmdMotors.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CmdMotors(genpy.Message):
  _md5sum = "3ee8ef12710d8d370ae71ac748657306"
  _type = "manta/CmdMotors"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool  startMotors
uint8 motorLeft
uint8 motorRight

"""
  __slots__ = ['startMotors','motorLeft','motorRight']
  _slot_types = ['bool','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       startMotors,motorLeft,motorRight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CmdMotors, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.startMotors is None:
        self.startMotors = False
      if self.motorLeft is None:
        self.motorLeft = 0
      if self.motorRight is None:
        self.motorRight = 0
    else:
      self.startMotors = False
      self.motorLeft = 0
      self.motorRight = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.startMotors, _x.motorLeft, _x.motorRight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.startMotors, _x.motorLeft, _x.motorRight,) = _struct_3B.unpack(str[start:end])
      self.startMotors = bool(self.startMotors)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.startMotors, _x.motorLeft, _x.motorRight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.startMotors, _x.motorLeft, _x.motorRight,) = _struct_3B.unpack(str[start:end])
      self.startMotors = bool(self.startMotors)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
