"""autogenerated by genpy from manta/Imu.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Imu(genpy.Message):
  _md5sum = "7833a28c21b52638fe9f1652c911d12c"
  _type = "manta/Imu"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Header header
float32 acc_x
float32 acc_y
float32 acc_z
float32 magn_x
float32 magn_y
float32 magn_z
float32 gyro_x
float32 gyro_y
float32 gyro_z
float64[9] linear_acceleration_covariance
float64[9] angular_velocity_covariance
float64[9] orientation_covariance
float64 direction


"""
  __slots__ = ['acc_x','acc_y','acc_z','magn_x','magn_y','magn_z','gyro_x','gyro_y','gyro_z','linear_acceleration_covariance','angular_velocity_covariance','orientation_covariance','direction']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float64[9]','float64[9]','float64[9]','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       acc_x,acc_y,acc_z,magn_x,magn_y,magn_z,gyro_x,gyro_y,gyro_z,linear_acceleration_covariance,angular_velocity_covariance,orientation_covariance,direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imu, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.magn_x is None:
        self.magn_x = 0.
      if self.magn_y is None:
        self.magn_y = 0.
      if self.magn_z is None:
        self.magn_z = 0.
      if self.gyro_x is None:
        self.gyro_x = 0.
      if self.gyro_y is None:
        self.gyro_y = 0.
      if self.gyro_z is None:
        self.gyro_z = 0.
      if self.linear_acceleration_covariance is None:
        self.linear_acceleration_covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      if self.angular_velocity_covariance is None:
        self.angular_velocity_covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      if self.orientation_covariance is None:
        self.orientation_covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      if self.direction is None:
        self.direction = 0.
    else:
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.magn_x = 0.
      self.magn_y = 0.
      self.magn_z = 0.
      self.gyro_x = 0.
      self.gyro_y = 0.
      self.gyro_z = 0.
      self.linear_acceleration_covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      self.angular_velocity_covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      self.orientation_covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      self.direction = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_9f.pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.magn_x, _x.magn_y, _x.magn_z, _x.gyro_x, _x.gyro_y, _x.gyro_z))
      buff.write(_struct_9d.pack(*self.linear_acceleration_covariance))
      buff.write(_struct_9d.pack(*self.angular_velocity_covariance))
      buff.write(_struct_9d.pack(*self.orientation_covariance))
      buff.write(_struct_d.pack(self.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.magn_x, _x.magn_y, _x.magn_z, _x.gyro_x, _x.gyro_y, _x.gyro_z,) = _struct_9f.unpack(str[start:end])
      start = end
      end += 72
      self.linear_acceleration_covariance = _struct_9d.unpack(str[start:end])
      start = end
      end += 72
      self.angular_velocity_covariance = _struct_9d.unpack(str[start:end])
      start = end
      end += 72
      self.orientation_covariance = _struct_9d.unpack(str[start:end])
      start = end
      end += 8
      (self.direction,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_9f.pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.magn_x, _x.magn_y, _x.magn_z, _x.gyro_x, _x.gyro_y, _x.gyro_z))
      buff.write(self.linear_acceleration_covariance.tostring())
      buff.write(self.angular_velocity_covariance.tostring())
      buff.write(self.orientation_covariance.tostring())
      buff.write(_struct_d.pack(self.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.magn_x, _x.magn_y, _x.magn_z, _x.gyro_x, _x.gyro_y, _x.gyro_z,) = _struct_9f.unpack(str[start:end])
      start = end
      end += 72
      self.linear_acceleration_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 72
      self.angular_velocity_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 72
      self.orientation_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 8
      (self.direction,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d = struct.Struct("<d")
_struct_9d = struct.Struct("<9d")
_struct_9f = struct.Struct("<9f")
