// Generated by gencpp from file manta/Radio.msg
// DO NOT EDIT!


#ifndef MANTA_MESSAGE_RADIO_H
#define MANTA_MESSAGE_RADIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manta
{
template <class ContainerAllocator>
struct Radio_
{
  typedef Radio_<ContainerAllocator> Type;

  Radio_()
    : message(0)
    , valeur1(0)
    , valeur2(0)  {
    }
  Radio_(const ContainerAllocator& _alloc)
    : message(0)
    , valeur1(0)
    , valeur2(0)  {
    }



   typedef uint8_t _message_type;
  _message_type message;

   typedef uint8_t _valeur1_type;
  _valeur1_type valeur1;

   typedef uint8_t _valeur2_type;
  _valeur2_type valeur2;




  typedef boost::shared_ptr< ::manta::Radio_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manta::Radio_<ContainerAllocator> const> ConstPtr;

}; // struct Radio_

typedef ::manta::Radio_<std::allocator<void> > Radio;

typedef boost::shared_ptr< ::manta::Radio > RadioPtr;
typedef boost::shared_ptr< ::manta::Radio const> RadioConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manta::Radio_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manta::Radio_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manta

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'manta': ['/home/pi/my_catkin_ws/src/manta/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manta::Radio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manta::Radio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manta::Radio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manta::Radio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manta::Radio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manta::Radio_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manta::Radio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2429ef2946c76f9c323459f6315b9f76";
  }

  static const char* value(const ::manta::Radio_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2429ef2946c76f9cULL;
  static const uint64_t static_value2 = 0x323459f6315b9f76ULL;
};

template<class ContainerAllocator>
struct DataType< ::manta::Radio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manta/Radio";
  }

  static const char* value(const ::manta::Radio_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manta::Radio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 message\n\
uint8 valeur1\n\
uint8 valeur2\n\
";
  }

  static const char* value(const ::manta::Radio_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manta::Radio_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.valeur1);
      stream.next(m.valeur2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Radio_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manta::Radio_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manta::Radio_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.message);
    s << indent << "valeur1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valeur1);
    s << indent << "valeur2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valeur2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANTA_MESSAGE_RADIO_H
